### ISSUE TITLE
Stwórz  QuantityCheckingList

### ISSUE THREAD

**Issue by jkiljanski** [jkiljanski/lukas-learn#10]
Lista będzie używana do prostego segregowania wsadzonych elementów. Powinna być podtypem naszej listy (ArrayListy).

W nowym podtypie dodaj metodę (getCuantityOfEachObject), która policzy elementy w liście wg typów i zwróci mapę obiekt->liczność, czyli prosty test: dodaj Stringi: a,b,c,a,b,d i powinien zwrócić mapę {(a,2,),(b,2),(c,1),(d,1)}

**Comment by jkiljanski** [comment]
To wymaga jeszcze poprawki testu i samej logiki. Zwróć uwagę po czym iterujesz. Nie powinieneś po keySecie tylko po elementach dodanych do listy

**Comment by ldabrowa** [comment]
Jaki mi napisałeś że iteruję po pustej mapie to załapałem jaki błąd zrobiłem.
Teraz działa i strasznie się cieszę.
ps. Walczę ze swoimi projektami pracowymi ale wyszukuje czas żeby pisać. Nie zawsze jednak uda się siedzieć w pociągu.
