### ISSUE TITLE
Dodanie repozytorium krów.

### ISSUE THREAD

**Issue by jkiljanski** [jkiljanski/lukas-learn#11]
Utwórz klasę CowHerdService, która będzie zarządzała stadem krów (utwórz obiekt Cow).

Cow powinien póki co mieć cechę rasa.

Ten serwis będzie tymczasowym repozytorium krów. Potem przeniesiemy je do bazy danych.

Dodaj do serwisu metodę do pobierania krów wg rasy (zwracana jest mapa).

Dodaj testy w celu dodania, zabrania i zwrócenia ilości krów, używając tego serwisu. Nie pisz innych testów. Interesuje nas tylko całosciowe testowanie.

Zblokowane przez #10

**Comment by jkiljanski** [comment]
teraz to zrób

**Comment by ldabrowa** [comment]
Jeśli jest oki to przechodzę do kolejnego punktu.
Do testów dodałem sobie QuantityCheckingList którego nie ma w tej gałęzi.
Działało.
Do zadania 12 wolałbym zrobić branch z mastera po merge.

**Comment by jkiljanski** [comment]
w gicie nie ma potrzeby na czekanie na merge, gdyż możesz to zrobić później. Pracę rozpocznij teraz opierając się na zmianach, które już zrobiłeś (czyli zrób odnogę od aktualnego commita). Najwyżej potem zmiany te wypierdaczysz, jak nie będą potrzebne.

**Comment by ldabrowa** [comment]
Tak się nakręciłem, że mi się udało, że już zacząłem wczoraj #12  :p . Zmergowałem mastera do #11 żeby mieć quantityCheckingList i jadę.
Z perspektywy dnia dzisiejszego moje nocne pytanie było idiotyczne, ale była to kwestia, która zablokowała mnie totalnie, pomimo  że oczywista. Po tym wyjaśnieniu poszło z górki.
Dzięki. Umysł jest czasem zadziwiający.
