### ISSUE TITLE
FIX: Fixing "copy paste" in three metods

### ISSUE THREAD

**Issue by ldabrowa** [jkiljanski/lukas-learn#4]
In this issue i try to fix metods :contains, indexOf and lastIndexOf. There is a similar code and i try to extract common logic to make code simple. FIX after jkiljanski code revision.

**Comment by ldabrowa** [comment]
Question:
I use git as my history. When i finished my work i make pull request with final work.
Is it right, that all points of my work are visible in this request? I thought that only last one will be delivered to server.
Waiting for your's comments.
Łukasz

**Comment by jkiljanski** [comment]
pull request is a request of merging you branch to master. Your branch has a lot of commits, so every one of them will be visible,

**Comment by jkiljanski** [comment]
One more rule: przejdźmy na język polski. Kod jest pisany po angielsku i tak powinno być. Również commity. Ale wszystko co jest poza tym, czyli githubowa obsługa i cała faza pull requestów - nie.

**Comment by ldabrowa** [comment]
Poprawka zrobiona zgodnie z sugestią. Zrobiłem dodatkową metodę prywatną.
